const express = require('express')
const router = express.Router()
const auth = require('../middleware/auth')
const bcrypt = require('bcrypt')
    
router.get('/', auth.checkNotAuthenticated, (req, res) => {
    res.render('register.ejs')
})

router.post('/', auth.checkNotAuthenticated, async (req, res) => {
    try {
        const hashedPassword = await bcrypt.hash(req.body.password, 10)
        users.push({
            id: Date.now().toString(), //should be automatically generated by database
            name: req.body.name,
            email: req.body.email,
            password: hashedPassword
        })
        res.redirect('/login')
    } catch {
        res.redirect('/register')
    }
    console.log(users)
})

module.exports = router